# Generated by Django 6.0.4 on 2026-05-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=100, verbose_name='Город проживания')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('experience_years', models.IntegerField(verbose_name='Опыт работы (лет)')),
                ('desired_salary', models.IntegerField(verbose_name='Желаемая зарплата (KGS)')),
                ('skills', models.TextField(verbose_name='Ключевые навыки')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фотография соискателя')),
                ('resume_file', models.FileField(upload_to='resumes/', verbose_name='Файл резюме (PDF/Docx)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
