# Generated by Django 6.0.4 on 2026-05-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horse_tour', '0003_company_companyservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='your full name: ')),
                ('number_card', models.PositiveIntegerField(default='12345678')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.company', verbose_name='choose the company for horse tour')),
            ],
        ),
    ]
