# Generated by Django 6.0.4 on 2026-05-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='photo',
            field=models.ImageField(null=True, upload_to='orders/'),
        ),
    ]
