# Generated by Django 6.0.4 on 2026-05-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='напишите имя автора')),
                ('title', models.CharField(max_length=50, verbose_name='напишите назвнание книги')),
                ('age_limit', models.PositiveIntegerField(default=0, verbose_name='Возрастное ограничение')),
                ('description', models.TextField(blank=True, verbose_name='напишите краткое описание')),
                ('release_date', models.DateField(verbose_name='укажите дату публикации')),
                ('image', models.ImageField(upload_to='book/', verbose_name='загрузите обложку книги')),
                ('book_file', models.FileField(upload_to='book/', verbose_name='загрузите pdf файл')),
                ('quantity', models.PositiveIntegerField(default=20, null=True, verbose_name='укажите количество страниц')),
                ('type_book', models.CharField(choices=[('художественная литература', 'художественная литература'), ('бизнес', 'бизнес'), ('Медицина', 'Медицина'), ('программирование', 'программирование'), ('Саморазвитие', 'Саморазвитие'), ('детская литература', 'детская литература'), ('классика', 'классика'), ('психология', 'психология')], default='классика', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
