# Generated by Django 6.0.4 on 2026-05-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('choice_human', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.human')),
            ],
        ),
    ]
