# Generated by Django 6.0.4 on 2026-05-05 06:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Оценка только от 1 до 5'), django.core.validators.MaxValueValidator(5, message='Оценка только от 1 до 5')])),
                ('text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('choice_human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='horse_tour.human')),
            ],
        ),
    ]
